### ISSUE TITLE
Non combat skills?

### ISSUE THREAD

**Issue by WesleyM77** [XrioBtw/effectivelevel-plugin#1]
Would be cool if this also applied to non-combat skills. For example, wearing the celestial ring gives +4 invisible mining boost.

**Comment by XrioBtw** [comment]
Thank you for the suggestion. This has now been implemented for celestial ring/signet (+4 mining), crystal saw (+3 construction) and the skilling guilds (+7 fishing, mining, woodcutting), and will be available in the plugin as soon as a developer has reviewed and added it to the client.
