### ISSUE TITLE
Void causing issues

### ISSUE THREAD

**Issue by PJGJ210** [XrioBtw/effectivelevel-plugin#4]
With void in inventory the invisible boost appears. I would think the show void equip bonus would appear when equipped vs in inv. 

![image](https://user-images.githubusercontent.com/16944807/213894687-5c097957-292b-4910-8fe5-7ed15a2d3526.png)
![image](https://user-images.githubusercontent.com/16944807/213894692-14751e62-39e3-45f9-8964-ae953b01b094.png)
![image](https://user-images.githubusercontent.com/16944807/213894767-b07543fb-d4d4-47e5-bcfc-37fbdb15f230.png)

Equipping (note I did have a waning ranging potion)
![image](https://user-images.githubusercontent.com/16944807/213894701-834eda71-1bf8-45cc-911d-06bc51e5a804.png)
![image](https://user-images.githubusercontent.com/16944807/213894774-1ba89b51-7149-49e9-a20c-76ee52d97cd5.png)
![image](https://user-images.githubusercontent.com/16944807/213894702-c851d9c8-c95f-4af8-8570-e4e71914e44e.png)

Only magic in inv (range helm equipped)
![image](https://user-images.githubusercontent.com/16944807/213894709-bc9ed005-4f74-49fb-9f92-31a7b92127cc.png)
![image](https://user-images.githubusercontent.com/16944807/213894714-627db9e9-6067-43d2-8a12-700ec11f5340.png)
![image](https://user-images.githubusercontent.com/16944807/213894717-37b631dc-df51-4a7f-9168-953bf8bbfe88.png)

**Comment by XrioBtw** [comment]
I fixed this problem in [version 1.2](https://github.com/XrioBtw/effective-level/commit/e1013baeb792b29258cef67579dc7ff30dd086b2)
