### ISSUE TITLE
"Show void equipment bonus"  - does not work with Shattered kits

### ISSUE THREAD

**Issue by PetGirlBecky** [XrioBtw/effectivelevel-plugin#5]
When my void is "Void ranger help (or)" from the "Shattered relics void ornament kit" the "Show void equipment bonus" feature does not work anymore.

**Comment by XrioBtw** [comment]
This was fixed in [version 1.3](https://github.com/XrioBtw/effective-level/compare/e1013baeb792b29258cef67579dc7ff30dd086b2...XrioBtw:07404510fb653db14c9bdb1b7688400904a80b87), and will be live in the client in one or two weeks once it has been reviewed.
